version: '3'
services:
  wps:
    build: .
    image: pacificclimate/dash-dv-explorer
    ports:
      - "30022:8050"
networks:
  default:
    external:
      name: pcicbr0

# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm