version: '3.2'
services:
  dv-explorer-prod:
    image: pcic/dash-dv-explorer
    container_name: dv-explorer-prod
    ports:
      - "30020:5000"
    volumes:
      - type: bind
        source: /storage/data/projects/comp_support/dv-explorer/data/
        target: /app/dve/data/
        read_only: true
      - type: bind
        source: ./config.yml
        target: /app/config.yml
        read_only: true

        # Download files: presently are permanent so best stored in an
        # external mount where old ones can be deleted periodically.
        # TODO: Remove after upgrading to use temporary files
      - type: bind
        source: ./downloads
        target: /downloads

networks:
  default:
    external:
      name: pcicbr0
